DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
       `UserID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
       `FirstName` VARCHAR(100) NOT NULL,
       `LastName` VARCHAR(100) NOT NULL,
       `Email` VARCHAR(100) NOT NULL,
       `Password` VARCHAR(40) NOT NULL,
       `Salt` VARCHAR(20) NOT NULL,
       
       UNIQUE KEY `Email` (`Email`)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `Tasks`;

CREATE TABLE `Tasks` (
	`TaskID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`UserID` BIGINT UNSIGNED NOT NULL,
	`Month` INT UNSIGNED NOT NULL,
	`Day` INT UNSIGNED NOT NULL,
	`Year` INT UNSIGNED NOT NULL,
	`Done` BOOLEAN NOT NULL,
	`Title` VARCHAR(200) NOT NULL,
	`Description` VARCHAR(500)
)ENGINE=MyISAM DEFAULT CHARSET=latin1;